### ISSUE TITLE
Kok source code website tapi python 100%?

### ISSUE THREAD

**Issue by andrect** [id-python/id-python#1]

**Comment by iromli** [comment]
hello @andrect, saya rasa yang menentukan "python 100%" adalah GitHub (ref: https://github.com/github/linguist) :wink: 

seingat saya, website python.or.id dulunya menggunakan proyek ini (berbasis django), tapi sekarang kita menggunakan 3rd-party blogging platform.

**Comment by andrect** [comment]
oh ok
